# Basic site settings
title: Pocket Flow

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "https://github.com/the-pocket/Tutorial-Codebase-Knowledge"
    
# Color scheme
color_scheme: light

# Author settings
author:
    name: Zachary Huang
    url: https://www.columbia.edu/~zh2408/
    twitter: ZacharyHuang12

# Mermaid settings
mermaid:
  version: "11.6.0"  # Pick the version you want
  # Default configuration
  config: |
    directionLR

# Callouts settings
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  best-practice:
    title: Best Practice
    color: green
  
# The custom navigation
nav:
  - Home: index.md       # Link to your main docs index
  - GitHub: "https://github.com/The-Pocket/Tutorial-Codebase-Knowledge"
  - Discord: "https://discord.gg/hUHHE9Sa6T"
